import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, decimal } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", { id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull() });
export const projects = mysqlTable("projects", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 160 }).notNull(), client: varchar("client", { length: 160 }), location: varchar("location", { length: 200 }), description: text("description"), status: mysqlEnum("status", ["planned", "active", "paused", "completed"]).default("planned").notNull(), ownerId: int("ownerId").notNull(), startDate: timestamp("startDate"), endDate: timestamp("endDate"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const workFronts = mysqlTable("work_fronts", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), name: varchar("name", { length: 160 }).notNull(), code: varchar("code", { length: 40 }), status: mysqlEnum("status", ["planned", "active", "attention", "blocked", "completed"]).default("planned").notNull(), progress: decimal("progress", { precision: 5, scale: 2 }).default("0").notNull(), currentState: text("currentState"), nextStep: text("nextStep"), advanceCondition: text("advanceCondition"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const services = mysqlTable("services", { id: int("id").autoincrement().primaryKey(), frontId: int("frontId").notNull(), name: varchar("name", { length: 160 }).notNull(), unit: varchar("unit", { length: 20 }).notNull(), plannedQty: decimal("plannedQty", { precision: 12, scale: 2 }).default("0").notNull(), executedQty: decimal("executedQty", { precision: 12, scale: 2 }).default("0").notNull(), status: varchar("status", { length: 40 }).default("planned").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const dailyLogs = mysqlTable("daily_logs", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), authorId: int("authorId").notNull(), logDate: timestamp("logDate").notNull(), summary: text("summary"), weather: varchar("weather", { length: 80 }), workforce: int("workforce"), workedHours: decimal("workedHours", { precision: 6, scale: 2 }), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const productionEntries = mysqlTable("production_entries", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), frontId: int("frontId").notNull(), serviceId: int("serviceId").notNull(), dailyLogId: int("dailyLogId"), quantity: decimal("quantity", { precision: 12, scale: 2 }).notNull(), unit: varchar("unit", { length: 20 }).notNull(), entryDate: timestamp("entryDate").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const events = mysqlTable("events", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), frontId: int("frontId"), serviceId: int("serviceId"), dailyLogId: int("dailyLogId"), title: varchar("title", { length: 200 }).notNull(), description: text("description"), category: varchar("category", { length: 40 }).notNull(), severity: mysqlEnum("severity", ["low", "medium", "high", "critical"]).default("medium").notNull(), status: varchar("status", { length: 40 }).default("open").notNull(), impact: text("impact"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const actions = mysqlTable("actions", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), eventId: int("eventId"), title: varchar("title", { length: 200 }).notNull(), ownerName: varchar("ownerName", { length: 160 }), dueAt: timestamp("dueAt"), priority: mysqlEnum("priority", ["low", "medium", "high", "critical"]).default("medium").notNull(), status: mysqlEnum("status", ["open", "in_progress", "done", "overdue"]).default("open").notNull(), completedAt: timestamp("completedAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const attachments = mysqlTable("attachments", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), dailyLogId: int("dailyLogId"), eventId: int("eventId"), actionId: int("actionId"), fileName: varchar("fileName", { length: 255 }).notNull(), fileKey: varchar("fileKey", { length: 500 }).notNull(), fileUrl: varchar("fileUrl", { length: 700 }).notNull(), mimeType: varchar("mimeType", { length: 120 }), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const decisions = mysqlTable("decisions", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), eventId: int("eventId"), frontId: int("frontId"), serviceId: int("serviceId"), title: varchar("title", { length: 200 }).notNull(), description: text("description"), decidedBy: varchar("decidedBy", { length: 160 }), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const notifications = mysqlTable("notifications", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), actionId: int("actionId"), recipientId: int("recipientId"), kind: varchar("kind", { length: 40 }).notNull(), title: varchar("title", { length: 200 }).notNull(), readAt: timestamp("readAt"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const summaries = mysqlTable("summaries", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), period: varchar("period", { length: 30 }).notNull(), content: text("content").notNull(), riskCount: int("riskCount").default(0).notNull(), generatedAt: timestamp("generatedAt").defaultNow().notNull() });

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert;
export type Project = typeof projects.$inferSelect; export type WorkFront = typeof workFronts.$inferSelect; export type Service = typeof services.$inferSelect; export type DailyLog = typeof dailyLogs.$inferSelect; export type ProductionEntry = typeof productionEntries.$inferSelect; export type Event = typeof events.$inferSelect; export type Action = typeof actions.$inferSelect;
