import { useMemo, useState } from "react";
import { AlertTriangle, ArrowUpRight, CalendarDays, Check, CircleDot, ChevronRight, Layers3, Plus, Radio, Search, TrendingUp, Wrench } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { useLocalProject } from "@/localStore";
import { usePilotLocation } from "@/pilotRouting";
import { getOperationalAttention } from "@/operationalInsights";

const Kicker = ({ children }: { children: React.ReactNode }) => <p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#71756f]">{children}</p>;
const Metric = ({ label, value, detail, icon, accent }: { label: string; value: string; detail: string; icon: React.ReactNode; accent?: string }) => <Card className="rounded-none border-0 bg-[#f6f6f3] shadow-[5px_5px_0_#d0d1cb]"><CardContent className="relative p-5"><div className={`absolute right-5 top-5 grid h-9 w-9 place-items-center ${accent === "amber" ? "bg-[#f1dfc5] text-[#b67b2c]" : accent === "red" ? "bg-[#f4d7d3] text-[#b84f42]" : "bg-[#e5efd0] text-[#789249]"}`}>{icon}</div><Kicker>{label}</Kicker><p className="mt-4 text-4xl font-black tracking-[-0.08em]">{value}</p><p className="mt-1 text-xs text-[#777c74]">{detail}</p></CardContent></Card>;

export default function Home() {
  const [, navigate] = usePilotLocation();
  const { project, toggleAction, addDiary } = useLocalProject();
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState(false);
  const [text, setText] = useState("");
  const actions = useMemo(() => project.actions.filter((action) => `${action.title} ${action.owner}`.toLowerCase().includes(query.toLowerCase())), [project.actions, query]);
  const done = project.actions.filter((action) => action.done).length;
  const front = project.fronts[0];
  const urgent = project.actions.filter((action) => !action.done).length;
  const attentionItems = useMemo(() => getOperationalAttention(project), [project]);

  const save = () => {
    if (!text.trim() || !front) return;
    addDiary({ date: new Date().toISOString(), frontId: front.id, service: front.name, summary: text.trim(), occurrence: "", weather: "Não informado", workforce: 0, hours: 0, production: 0 });
    setText(""); setOpen(false); toast.success("Registro salvo no diário");
  };

  return <div className="min-h-screen bg-[#ececea] px-4 py-6 sm:px-7 lg:px-10 lg:py-8"><div className="mx-auto max-w-[1500px]">
    <header className="mb-8 flex flex-col gap-5 border-b border-black/10 pb-6 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.24em] text-[#747870]"><span>Portfólio</span><ChevronRight className="h-3 w-3" /><span>Obra ativa</span></div><div className="flex items-start gap-4"><div className="hidden h-14 w-1 bg-[#202321] sm:block" /><div><h1 className="text-4xl font-black uppercase leading-[0.9] tracking-[-0.07em] text-[#202321] sm:text-6xl">{project.name}</h1><p className="mt-3 text-sm text-[#6e736c]">{project.description} <span className="mx-2">·</span> <span className="font-semibold text-[#8da65a]">{project.status}</span></p></div></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" className="h-10 border-black/15 bg-transparent text-xs font-bold uppercase tracking-[0.12em] hover:bg-white" onClick={() => navigate("/timeline")}><CalendarDays className="mr-2 h-4 w-4" /> Ver timeline</Button><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="h-10 bg-[#202321] text-xs font-bold uppercase tracking-[0.12em] text-white hover:bg-[#373b37]"><Plus className="mr-2 h-4 w-4" /> Registrar o dia</Button></DialogTrigger><DialogContent className="border-black/10 bg-[#f5f5f2]"><DialogHeader><DialogTitle className="text-2xl font-black uppercase tracking-[-0.04em]">O que aconteceu hoje?</DialogTitle></DialogHeader><Textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="Descreva a atividade, condição encontrada ou ocorrência..." className="min-h-32 border-black/10 bg-white" /><Button onClick={save} className="bg-[#202321] text-white">Salvar registro</Button></DialogContent></Dialog></div></header>
    <div className="mb-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Avanço da frente" value={`${Math.round(front?.progress ?? 0)}%`} detail={`${front?.name ?? "Sem frente"} · frente principal`} icon={<TrendingUp className="h-5 w-5" />} /><Metric label="Produção acumulada" value={`${(front?.executed ?? 0).toFixed(2)} ${front?.unit ?? "un"}`} detail={`${front?.name ?? "Produção"} · ${front?.code ?? ""}`} icon={<Layers3 className="h-5 w-5" />} /><Metric label="Impedimentos" value={`${project.events.filter((event) => event.status !== "Resolvido").length}`.padStart(2, "0")} detail="Eventos em tratamento" icon={<AlertTriangle className="h-5 w-5" />} accent="amber" /><Metric label="Ações em aberto" value={`${urgent}`.padStart(2, "0")} detail={`${done} concluída(s)`} icon={<CircleDot className="h-5 w-5" />} accent="red" /></div>
    <section className="mb-8"><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><Kicker>Centro de atenção</Kicker><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.04em]">O que exige acompanhamento</h2></div><p className="text-xs text-[#777c74]">Leitura automática dos dados locais</p></div>{attentionItems.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{attentionItems.map((item) => <button key={item.id} type="button" onClick={() => navigate(item.path)} className={`group min-h-40 border-l-4 p-5 text-left shadow-[5px_5px_0_#d0d1cb] transition hover:-translate-y-0.5 ${item.tone === "critical" ? "border-[#c95a4a] bg-[#f6f6f3]" : item.tone === "warning" ? "border-[#d89b45] bg-[#f6f6f3]" : "border-[#8da65a] bg-[#f6f6f3]"}`}><div className="flex items-start justify-between gap-3"><span className={`grid h-9 min-w-9 place-items-center px-2 text-lg font-black ${item.tone === "critical" ? "bg-[#c95a4a] text-white" : item.tone === "warning" ? "bg-[#f1dfc5] text-[#b67b2c]" : "bg-[#e5efd0] text-[#789249]"}`}>{String(item.count).padStart(2, "0")}</span><ArrowUpRight className="h-4 w-4 text-[#858a82] transition group-hover:text-[#202321]" /></div><h3 className="mt-5 text-sm font-black uppercase tracking-[-0.02em]">{item.label}</h3><p className="mt-2 text-xs leading-5 text-[#70756e]">{item.description}</p></button>)}</div> : <Card className="rounded-none border-0 border-l-4 border-l-[#8da65a] bg-[#f6f6f3] shadow-[5px_5px_0_#d0d1cb]"><CardContent className="flex items-center gap-3 p-5"><span className="grid h-10 w-10 place-items-center bg-[#e5efd0] text-[#789249]"><Check className="h-5 w-5" /></span><div><Kicker>Operação estabilizada</Kicker><p className="mt-1 text-sm font-semibold">Não há vencimentos, eventos críticos ou frentes ativas sem atualização recente.</p></div></CardContent></Card>}</section>
    <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><section className="min-w-0"><div className="mb-3 flex items-center justify-between"><div><Kicker>Leitura operacional</Kicker><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.04em]">Frentes de trabalho</h2></div><Button variant="ghost" className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#6d726b]" onClick={() => navigate("/frentes")}>Ver todas <ArrowUpRight className="ml-2 h-4 w-4" /></Button></div><div className="space-y-3">{project.fronts.map((item, index) => <Card key={item.id} className={`rounded-none border-0 bg-[#f6f6f3] shadow-[5px_5px_0_#d0d1cb] ${index === 0 ? "ring-1 ring-[#d89b45]/50" : ""}`}><CardContent className="p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center"><div className="flex flex-1 items-start gap-4"><div className={`grid h-11 w-11 shrink-0 place-items-center ${index === 0 ? "bg-[#d89b45] text-white" : "bg-[#dedfda] text-[#777b73]"}`}><span className="text-xs font-black">{String(index + 1).padStart(2, "0")}</span></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold uppercase tracking-[-0.02em]">{item.name}</h3><span className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#999d95]">{item.code}</span></div><p className="mt-1 text-sm text-[#70756e]">{item.detail}</p></div></div><div className="w-full md:w-48"><div className="mb-2 flex justify-between text-[10px] font-bold uppercase tracking-[0.12em]"><span>{item.status}</span><span>{item.progress}%</span></div><Progress value={item.progress} className="h-2 bg-[#dedfda]" /></div></div></CardContent></Card>)}</div></section>
    <section><div className="mb-3 flex items-end justify-between"><div><Kicker>Prioridade da operação</Kicker><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.04em]">Ações críticas</h2></div><Badge className="rounded-none bg-[#c95a4a] px-2 py-1 text-[9px] uppercase tracking-[0.14em] text-white">{urgent} prioritárias</Badge></div><Card className="rounded-none border-0 bg-[#202321] text-[#f3f3ef] shadow-[5px_5px_0_#c7c9c2]"><CardContent className="p-5"><div className="mb-4 flex items-center gap-2 border-b border-white/10 pb-4"><Radio className="h-4 w-4 text-[#d89b45]" /><span className="text-[10px] font-bold uppercase tracking-[0.18em] text-white/50">Plano de ação · local</span></div><div className="space-y-1">{actions.slice(0, 6).map((action) => <button key={action.id} onClick={() => { toggleAction(action.id); toast.success(action.done ? "Ação reaberta" : "Ação concluída"); }} className={`group flex w-full items-start gap-3 border-b border-white/10 py-3 text-left last:border-0 ${action.done ? "opacity-45" : ""}`}><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center border ${action.done ? "border-[#b8d36a] bg-[#b8d36a] text-[#202321]" : "border-white/25"}`}>{action.done && <Check className="h-3 w-3" />}</span><span className="min-w-0 flex-1"><span className={`block text-sm font-semibold ${action.done ? "line-through" : ""}`}>{action.title}</span><span className="mt-1 block text-[10px] uppercase tracking-[0.1em] text-white/40">{action.owner} · {action.due}</span></span><span className="mt-1 h-2 w-2 rounded-full bg-[#c95a4a]" /></button>)}</div><div className="mt-4 relative"><Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-white/35" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filtrar ações" className="h-9 border-white/10 bg-white/5 pl-9 text-xs text-white placeholder:text-white/30" /></div></CardContent></Card></section></div>
    <div className="mt-10 grid gap-5 lg:grid-cols-[1fr_1.2fr]"><Card className="rounded-none border-0 border-l-4 border-l-[#d89b45] bg-[#f6f6f3] shadow-[5px_5px_0_#d0d1cb]"><CardContent className="p-5"><Kicker>Estado atual</Kicker><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.04em]">Impedimento em tratamento</h2><div className="mt-5 flex items-start gap-4"><div className="grid h-10 w-10 shrink-0 place-items-center bg-[#f1dfc5] text-[#b67b2c]"><Wrench className="h-5 w-5" /></div><p className="text-sm leading-6 text-[#70756e]">{project.events.find((event) => event.status !== "Resolvido")?.impact ?? "Nenhum impedimento ativo registrado."}</p></div></CardContent></Card><Card className="rounded-none border-0 bg-[#f6f6f3] shadow-[5px_5px_0_#d0d1cb]"><CardContent className="p-5"><Kicker>Resumo local</Kicker><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.04em]">Últimos registros</h2>{project.diaries.length ? <p className="mt-5 text-sm text-[#70756e]">{project.diaries[0].summary}</p> : <p className="mt-5 text-sm text-[#70756e]">Nenhum diário local ainda. Registre o primeiro dia para iniciar o histórico da obra.</p>}</CardContent></Card></div>
  </div></div>;
}
