import { useState } from "react";
import { useLocalProject } from "@/localStore";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Building2, Plus } from "lucide-react";
import { toast } from "sonner";
const Kicker = ({ children }: { children: React.ReactNode }) => <p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#71756f]">{children}</p>;
export default function SetupPage() { const { project, addFront } = useLocalProject(); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [detail, setDetail] = useState(""); const save = () => { if (!name.trim()) return; addFront({ name, code: code || "SEM CÓDIGO", detail: detail || "Estado ainda não informado", progress: 0, status: "Planejada", executed: 0, planned: 100, unit: "%" }); setName(""); setCode(""); setDetail(""); toast.success("Frente cadastrada localmente"); }; return <div className="min-h-screen bg-[#ececea] p-5 sm:p-8 lg:p-12"><div className="mx-auto max-w-[1100px]"><Kicker>Configuração enxuta · uso próprio</Kicker><h1 className="mt-2 text-4xl font-black uppercase tracking-[-0.07em] sm:text-6xl">Cadastro rápido</h1><p className="mt-3 max-w-xl text-sm text-[#70756e]">Inclua novas frentes da {project.name} sem importar arquivos ou configurar servidor. Tudo fica salvo neste navegador.</p><div className="mt-8 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><Card className="rounded-none border-0 bg-[#202321] text-white shadow-[5px_5px_0_#c7c9c2]"><CardHeader><Kicker>Nova frente</Kicker><CardTitle className="mt-2 text-2xl font-black uppercase">Adicionar</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Nome da frente" className="border-white/15 bg-white/10 text-white placeholder:text-white/35" /><Input value={code} onChange={(e) => setCode(e.target.value)} placeholder="Código, ex.: TER-03" className="border-white/15 bg-white/10 text-white placeholder:text-white/35" /><Textarea value={detail} onChange={(e) => setDetail(e.target.value)} placeholder="Estado atual ou dependência" className="border-white/15 bg-white/10 text-white placeholder:text-white/35" /><Button onClick={save} disabled={!name.trim()} className="w-full bg-[#b8d36a] text-[#202321] hover:bg-[#c9e27c]"><Plus className="mr-2 h-4 w-4" /> Salvar frente</Button></CardContent></Card><Card className="rounded-none border-0 bg-[#f6f6f3] shadow-[5px_5px_0_#d0d1cb]"><CardContent className="p-6"><div className="flex items-center gap-3"><Building2 className="h-5 w-5 text-[#8da65a]" /><div><Kicker>Obra ativa</Kicker><p className="mt-1 text-xl font-black uppercase">{project.name}</p></div></div><div className="mt-6 space-y-2">{project.fronts.map((front) => <div className="flex items-center justify-between border-b border-black/10 py-3 text-sm" key={front.id}><span className="font-semibold">{front.name}</span><span className="font-mono text-[10px] text-[#7d827a]">{front.code} · {front.progress}%</span></div>)}</div></CardContent></Card></div></div></div>; }
